# Generated by Django 2.1.1 on 2019-04-19 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('secure_radius', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('lng', models.FloatField(blank=True, default=None, null=True)),
                ('mens', models.IntegerField(default=0)),
                ('girls', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(default='1', max_length=20)),
                ('tags', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tusa',
            unique_together={('name',)},
        ),
    ]
