# Generated by Django 2.1.1 on 2019-04-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mens', models.IntegerField(default=0)),
                ('girls', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=200)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Location')),
            ],
        ),
    ]
