# Generated by Django 2.1.1 on 2019-04-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tusa',
            name='date',
        ),
    ]
