# Generated by Django 2.1.1 on 2019-04-22 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_remove_tusa_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusa',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 10, 10, 3)),
        ),
    ]
