# Generated by Django 2.1.1 on 2019-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_tusa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tusa',
            name='geo',
        ),
        migrations.AddField(
            model_name='tusa',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tusa',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
