# Generated by Django 2.1.1 on 2019-04-20 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20190420_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='tusa',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 20, 20, 2, 27, 974674)),
        ),
    ]
