# Generated by Django 2.1.1 on 2019-04-20 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20190420_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusa',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 20, 20, 2, 39, 421153)),
        ),
    ]
