# Generated by Django 2.1.1 on 2019-04-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_tusa_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tusa',
            old_name='date',
            new_name='tusadate',
        ),
    ]
