# Generated by Django 2.1.1 on 2019-04-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20190420_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusa',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 20, 22, 24, 55, 495653)),
        ),
        migrations.AlterField(
            model_name='tusa',
            name='image',
            field=models.ImageField(upload_to='MEDIA'),
        ),
    ]
