# Generated by Django 2.1.1 on 2019-04-21 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20190420_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusa',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 27, 10, 10, 3)),
        ),
    ]
